### ISSUE TITLE
NetPrinter.connect(): java.lang.String cannot be cast to java.lang.Double

### ISSUE THREAD

**Issue by lucle1999** [HeligPfleigh/react-native-thermal-receipt-printer#47]
I get this error when I call the NetPrinter.connect() function. Can you give me 1 solution?

**Comment by HeligPfleigh** [comment]
Thanks you @lucle1999, this is a bug while bridging the native code to js, it should be fixed in commit `994395e7bec27d973dfdf235c79db38859d62cd8`. Could you try the latest version and share the result?

**Comment by lucle1999** [comment]
Thanks @HeligPfleigh  for your support. I have installed the latest version "react-native-thermal-receipt-printer": "^1.1.5",  but it still doesn't work with the same error.
